=== outmaneBH/2021_LMSGI_OB/ud04/Prueba/Modelo.xsd
<?xml version="1.0"?>
<!--
autor OUTMANE BOUHOU
Fecha  11/02/2021
descripcion .-validacion de elementos simples.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="Modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciclo"> 
                      <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="DAW"/>
                        <xs:enumeration value="ASIR"/>
                        <xs:enumeration value="DAM"/>
                        <xs:enumeration value="SMR"/>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
                <xs:element name="nombreciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
                <xs:element name="codigopostal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="collapse"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
                <xs:element name="temperatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:fractionDigits value="2"/>
                            <xs:totalDigits  value="5"/>
                            <xs:minInclusive  value="-50"/>
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
                <xs:element name="codigoasignatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="BD|LMSGI|PROG|EDD|FOL"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
                 <xs:element name="nombreciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100" />
                           <xs:pattern value="[A-ZÑ][a-zA-ZñÑ ]*"/>
                        </xs:restriction>
                   </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== outmaneBH/2021_LMSGI_OB/ud04/Prueba/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Modelo.xsd'>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreciclo>Desarollo de applicaciones web</nombreciclo>
    <codigopostal>49600</codigopostal>
    <comentario>Este ciclo es de DAW  </comentario>
    <temperatura>20</temperatura>
    <codigoasignatura>EDD</codigoasignatura>
    <profesor codP="ARN" mudolo="LMSGI">Amor Rodriguez</profesor>
  
</Modelo>
