=== outmaneBH/2021_LMSGI_OB/ud04/Dtd/11.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT catalogo (portátil*)>
<!ELEMENT portátil (referencia,nombre,fabricante,procesador,ram,disco,pantalla,gráfica,foto*)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fabricante EMPTY >
<!ATTLIST fabricante nombre ( LENOVO|HP|MSI|APPLE|ASUS|DELL|DESCONOCIDO ) #REQUIRED >
<!ELEMENT procesador (nombre,cache,numero,velocidad)>
<!ELEMENT cache (#PCDATA)>
<!ATTLIST cache tamanyo (Mb|Gb|Tb) "Gb">
<!ELEMENT numero (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ATTLIST velocidad medida CDATA #FIXED "Ghz">
<!ELEMENT ram (memoria,tipo)>
<!ELEMENT memoria (#PCDATA)>
<!ATTLIST memoria medida (Mb|Gb|Tb) "Gb">
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT disco (#PCDATA)>
<!ATTLIST disco tipo (SSD|HDD) #REQUIRED> 
<!ATTLIST disco medida (Mb|Gb|Tb) #REQUIRED > 
<!ELEMENT pantalla (dimensión,resolución,máxima?)>
<!ELEMENT dimensión (#PCDATA)>
<!ELEMENT resolución (#PCDATA)>
<!ELEMENT máxima (#PCDATA)>
<!ELEMENT gráfica (#PCDATA)>
<!ELEMENT foto (#PCDATA)>

=== outmaneBH/2021_LMSGI_OB/ud04/Dtd/XML11.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE catalogo SYSTEM '11.dtd'>

<catalogo 
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Shema/11_1.xsd'>
   <portátil> 
        <referencia>HP102219</referencia>
        <nombre>PORTATIL HP 15-DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombre>Intel Core i3-7020U</nombre>
            <cache tamanyo="Gb">3</cache>
            <numero>2</numero>
            <velocidad>5.3</velocidad>
        </procesador>
        <ram>
            <memoria medida="Gb">32</memoria>
            <tipo>DDR3</tipo>
        </ram>
        <disco tipo="SSD" medida="Gb">250</disco>
        <pantalla>
            <dimensión>15.6 pulgadas</dimensión>
            <resolución>1266x768</resolución>
            <máxima>1366x768</máxima>
        </pantalla>
        <gráfica>Intel UHD Graphics 620</gráfica>       
        <foto>foto1.png</foto>
        <foto>foto2.png</foto>       
    </portátil>
</catalogo>
