=== outmaneBH/2021_LMSGI_OB/ud04/05.dtd
<!ELEMENT Firstname (#PCDATA) >
<!ELEMENT Lastaname (#PCDATA) >
<!ELEMENT ContactNo (#PCDATA) >
<!ELEMENT Email (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT State (#PCDATA) >
<!ELEMENT Zip (#PCDATA) >
<!ELEMENT Adress (city,State,Zip) >
<!ELEMENT employee (Firstname,Lastaname,ContactNo?,Email+,Adress)>
<!ELEMENT company (employee) >

=== outmaneBH/2021_LMSGI_OB/ud04/XML05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM '05.dtd'>

<company>
<employee>
<Firstname>Outmane</Firstname>
<Lastaname>Bouhou</Lastaname>
<ContactNo>51245678</ContactNo>
<Email>outmane.bouho@gmail.com</Email>
<Adress>
    <city>Benvente</city>
    <State>Zamora</State>
    <Zip>49600</Zip>
</Adress>
</employee>
</company>
