
<!DOCTYPE hechoHistoricos[
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT fecha (dia,mes,anyo)>
<!ELEMENT description (nombre,fecha)>
<!ELEMENT hechoHistoricos (description+) >
]> 
<hechoHistoricos>
    <description>
        <nombre>Se funda Youtube</nombre>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </description>
    <description>
        <nombre>Se funda Google</nombre>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </description>
     <description>
        <nombre>Se funda Facebook</nombre>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </description>
</hechoHistoricos>

